FROM apache/superset:latest

USER root

# Installation du driver PostgreSQL indispensable pour la connexion
RUN pip install --no-cache-dir psycopg2-binary

# Revenir à l'utilisateur par défaut pour la sécurité
USER superset