FROM apache/superset:latest

USER root

# Dépendances système nécessaires
RUN apt-get update && apt-get install -y \
    libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*

# Installer support PostgreSQL complet Superset
RUN pip install --upgrade pip \
    && pip install "apache-superset[postgres]"

USER superset
